---
# check /install required tools for this role

# gather facts for the host it is delegated to
- name: Run setup to gather variables
  ansible.builtin.setup:

- name: Check pip tools
  ansible.builtin.pip:
    name:
      - pyvmomi
      - netaddr
      - requests

- name: Packages
  ansible.builtin.package:
    state: present
    name:
      - qemu-img
  when: ansible_os_family != "Darwin"

- name: Packages on RedHat/CentOS/Almalinux/etc
  ansible.builtin.package:
    state: present
    name:
      - genisoimage
      - python3-netaddr
      - bind-utils
  when: ansible_os_family == "RedHat"

- name: Packages on mac
  ansible.builtin.homebrew:
    state: present
    name:
      - qemu
      - cdrtools
  when: ansible_os_family == "Darwin"

- name: External tool ovftool needs to be installed
  ansible.builtin.shell: ovftool --version
  register: ovftoolreg
  failed_when: "'VMware ovftool' not in ovftoolreg.stdout"
  changed_when: false
