---
# check /install required tools for this role

# gather facts for the host it is delegated to
- name: run setup to gather variables
  setup:

- name: check pip tools
  pip:
    name:
      - pyvmomi
      - netaddr

- name: packages
  package:
    state: present
    name:
      - qemu-img
  when: ansible_os_family != "Darwin"

- name: packages on RedHat/CentOS/OracleLinux
  package:
    state: present
    name:
      - genisoimage
      - python3-netaddr
      - bind-utils
  when: ansible_os_family == "RedHat"

- name: packages on mac
  homebrew:
    state: present
    name:
      - qemu
      - cdrtools
  when: ansible_os_family == "Darwin"

- name: ovftool needs to be installed
  shell: ovftool --version
  register: ovftoolreg
  failed_when: "'VMware ovftool' not in ovftoolreg.stdout"
  changed_when: false
